### ekf_node config file ###
ekf_filter_node:
    ros__parameters:
        frequency: 30.0
        two_d_mode: true
        publish_acceleration: false
        publish_tf: true
        
        # Frames
        map_frame: map              # Defaults to "map" if publish_tf is true
        odom_frame: odom            # Parent frame
        base_link_frame: base_link  # Child frame
        world_frame: odom           # The frame to calculate relative to

        # input 1: Wheel Odometry (from diff_drive_controller)
        odom0: /diff_drive_base_controller/odom_fixed
        odom0_config: [false, false, false,
                       false, false, false,
                       true,  true,  false,
                       false, false, true,
                       false, false, false]
        # We only use velocities (vx, vy, vyaw) from wheel odom because position drifts
        odom0_queue_size: 10
        odom0_differential: false

        # input 2: IMU (from Gazebo Bridge)
        # imu0: /imu
        # imu0_config: [false, false, false,
        #               true,  true,  true,
        #               false, false, false,
        #               true,  true,  true,
        #               true,  true,  true]
        # We use orientation, angular velocity, and linear acceleration
        # imu0_differential: false
        # imu0_queue_size: 10
        # imu0_remove_gravitational_acceleration: true